### ISSUE TITLE
Lambda runs once then fails

### ISSUE THREAD

**Issue by henryhuangh** [thefinnomenon/graphql-algolia-transformer#13]
Great work on the transformer by the way.

After setting up the transformer, only the first record goes through. Upon investigating the event logs, I found that the error was coming from, blocking the code from running further
https://github.com/thefinnomenon/graphql-algolia-transformer/blob/52a55f22707bae50df99e9ceece11702fb294d51/algolia-lambda/python_algolia_function.py#L80

I also noticed that indeed the settings key was removed and was done so in line 82
https://github.com/thefinnomenon/graphql-algolia-transformer/blob/52a55f22707bae50df99e9ceece11702fb294d51/algolia-lambda/python_algolia_function.py#L82

So any subsequent runs will be void of the settings key halting any further updates.

Can you explain the reason for removing the settings key? Also I was able to fix it by changing lines76 to 84 to 
```python
def set_index_settings(index_name, opts):
    if 'settings' not in opts:
        return
    logger.debug('Configuring Index: %s', opts)
    settings = opts['settings']
    opts.pop('settings')
    index = client.init_index(index_name)
    index.set_settings(settings, opts).wait()``

**Comment by thefinnomenon** [comment]
I am going to close this issue but let me know if it is still occurring in v2.
