### ISSUE TITLE
Ready this transformer plugin for GraphQL Transformer v2

### ISSUE THREAD

**Issue by renebrandel** [thefinnomenon/graphql-algolia-transformer#6]
👋  This is Rene from the AWS Amplify team! First off, **THANK YOU** for your amazing plugin! 

I have some great news to share, we've rewritten the GraphQL Transformer plugin from the ground up to take advantage of some really amazing capabilities. All the details here: https://github.com/aws-amplify/amplify-cli/issues/6217#issuecomment-929677992 

### How to migrate your plugin to GraphQL Transformer v2
In order to make this plugin forward compatible with GraphQL Transformer v2, you need to make some tiny adjustments to the classes you inherit from. Migration steps here: https://gist.github.com/renebrandel/0b9537e2016e3dd9ed6d794b30b2e3f4

Happy to also hop on a call with you to walk you through the process. Email me at any time: renbran at amazon dot com

**Comment by BernhardSmuts** [comment]
Any movement on this?

**Comment by thefinnomenon** [comment]
I'm not using Amplify or this transformer anymore but if someone wants to handle the migration & open a PR I will merge it.
